name: CI

on:
  push:
    branches: [dev, test]
  pull_request:
    branches: [dev, test]

jobs:
  build-test:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/test'
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

  build-dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

  deploy-test:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/test'
    steps:
      - run: echo "Deploy ${{ github.ref }} to server"

  deploy-dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
      - run: echo "Deploy ${{ github.ref }} to server"
